name: Swift

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: CocoaPod Install
      run: pod install
    - name: Force XCode 11
      run: sudo xcode-select -switch /Applications/Xcode_11.3.app
    - name: iPhone 11 Test
      run: |
        xcodebuild test -scheme SwiftDiExampleTests -workspace SwiftDiExample.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.3' -enableCodeCoverage YES
        bash <(curl -s https://codecov.io/bash)
